events {}

http {

    upstream login_service {
        server login-service:3000;
    }

    upstream product_service {
        server product-service:3001;
    }

    upstream order_service {
        server order-service:3002;
    }

    server {

        listen 80;

        location /login {
            proxy_pass http://login_service/login;
        }

        location /products {
            proxy_pass http://product_service/products;
        }

        location /orders {
            proxy_pass http://order_service/orders;
        }

    }

}