apiVersion: apps/v1
kind: Deployment

metadata:
  name: login-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: login-service

  template:
    metadata:
      labels:
        app: login-service

    spec:
      containers:

      - name: login-service
        image: festiana3110/uascc-login-service:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 3000

        env:

        - name: DB_HOST
          value: postgres

        - name: DB_USER
          value: admin

        - name: DB_PASSWORD
          value: admin123

        - name: DB_NAME
          value: uas_cloud

        - name: DB_PORT
          value: "5432"

        - name: JWT_SECRET
          value: secret123

---

apiVersion: v1
kind: Service

metadata:
  name: login-service

spec:

  selector:
    app: login-service

  ports:

  - port: 3000
    targetPort: 3000